### PR TITLE
Date to datetime

### PR DESCRIPTION
**Pull request by vladistan**
First attempt at using datetime instead of dates

### CODE REVIEW

**Comment by debajyotid2** [comment]
@vladistan @AdamFinkle Pytest appears to be failing
```
ERROR tests/test_rules_engine/test_engine.py::test_convert_to_intermediate_billing_periods - KeyError: 'analysis_type_override'
ERROR tests/test_rules_engine/test_engine.py::test_get_outputs_normalized - KeyError: 'analysis_type_override'
```
because of the way normalized billing period instances are initialized.
```python
        # billing_periods = [
        #     NormalizedBillingPeriodRecordBase(**x) for x in billing_periods_dict
        # ]
    
>       billing_periods = [
            NormalizedBillingPeriodRecordBase(
                period_start_date=date.fromisoformat(x["period_start_date"]),
                period_end_date=date.fromisoformat(x["period_end_date"]),
                usage=x["usage"],
                analysis_type_override=x["analysis_type_override"],
                inclusion_override=x["inclusion_override"],
            ) for x in billing_periods_dict
        ]
```
versus
```python
    billing_periods = [
        NormalizedBillingPeriodRecordBase(**x) for x in billing_periods_dict
    ]
```

**Comment by vladistan** [comment]
Ahh,  you enabled the workflow.  Let us examine what's going on.   We run all the tests in our codespace before creating the PR and all the tests were passing.   Something is different.

FYI,  the reason we changed the way that  `NormalizedBillingPeriodRecordBase` are created is because pydantic was choking on your test data.  Now that we have datetime instead of date, pydantic expects start_date and end_date to be in ISO timestamp format which is '2024-10-09T05:23:11

when you explicitly instantiate the objects with the constructor instead of using **x  you can supply your own parsers for each field.   

let us dig deeper into this

**Comment by vladistan** [comment]
@debajyotid2 @thadk I put a few fixes,  could you approve the workflow to see how it goes?

**Comment by debajyotid2** [comment]
Nice - the rules engine unit tests are passing! 

The pyodide tests still fail because the dates are not being converted into datetime objects while parsing.  This is because in `TemperatureInput`  we do not have a parser defined to convert date strings to datetime, and we cannot instantiate `TemperatureInput` objects by directly calling the constructor (as is being done now in `pyodide  we'll still need to change the way date strings are being parsed in [`pyodide.test.ts`](https://github.com/codeforboston/home-energy-analysis-tool/blob/main/heat-stack/app/utils/pyodide.test.ts). @thadk do you think we need to fix this before merging?

**Pull request closed without merging**
