### PR TITLE
Epic stack

### PR DESCRIPTION
**Pull request by thadk**
Basic pyodide setup for [Epic Stack](https://www.epicweb.dev/epic-stack)
image

- [x] Rebased and added numpy dependency to `public/pyodide-env` environment. 
- [x] Patched a basic loader into to epic-stack's Remix-run to open a `.py` file into a js string.

### CODE REVIEW

**Comment by thadk** [comment]
- [ ] I think we need to add `?raw` to the end of the python import in javascript:
https://vitejs.dev/guide/assets.html#importing-asset-as-string

**Comment by thadk** [comment]
I found instructions about how to patch with a new file type here: `https://github.com/remix-run/remix/discussions/2468#discussioncomment-2639271` and guessing it mostly works when I combined it with the other loader.ts file [here](https://github.com/remix-run/remix/pull/3985/files#diff-a9488b95882e42c9908c223b503cf1a01ad8bf1e15a3a14711c9f770f6476de8)

**Comment by plocket** [comment]
We got it working for me. I'd love if we can try it one more time on a fresh environment.

**Review by plocket — APPROVED** [review]
We've tried it out and it looks good to me!

**Pull request merged**
