### PR TITLE
Added makefile to rules engine

### PR DESCRIPTION
**Pull request by alanisaac**
I'm finding it's somewhat difficult to share pre-commit hooks in a project.  In lieu of that directly, this `makefile` consolidates everything into one step, so developers do not have to remember all the commands in CI.

Run `make all` from the rules-engine folder and it will check everything that CI checks.

### CODE REVIEW

**Comment by alanisaac** [comment]
> Should we update CI to use Makefile to remove duplication?

Yeah, that's a good idea.

**Comment by alanisaac** [comment]
@jkwan2011 done

**Review by jkwan2011 — APPROVED** [review]

**Comment by jkwan2011** [comment]
Nit: Rename to `Makefile` by convention

**Comment by alanisaac** [comment]
> Nit: Rename to Makefile by convention

TIL: https://stackoverflow.com/a/12686411

> Normally you should call your makefile either makefile or Makefile. (We recommend Makefile because it appears prominently near the beginning of a directory listing, right near other important files such as README.)

**Review by axiomizer — COMMENTED** [review]
I'm late to the party, but looks good to me

**Pull request merged**
