### PR TITLE
Use string enums for natural gas company

### LINKED ISSUE #167: Use string enums for NaturalGasCompany
Use Python string enums for NaturalGasCompany.  This makes it easier for the javascript team.

### PR DESCRIPTION
**Pull request by alanisaac**
Fixes #167

### CODE REVIEW

**Review by plocket — COMMENTED** [review]
I'm a fan in general. I'm curious why there are two arguments to the function now. Is that just a python typing thing?

**Comment by alanisaac** [comment]
> I'm a fan in general. I'm curious why there are two arguments to the function now. Is that just a python typing thing?

I assume in reference to this:

```py
class NaturalGasCompany(str, Enum):
```

This is a class definition, and in this case, this is a class implementing [multiple inheritance](https://www.programiz.com/python-programming/multiple-inheritance).  As to why we use it here, that's the recommended solution for making [string-backed enums](https://stackoverflow.com/questions/58608361/string-based-enum-in-python).

**Comment by ddebnath-nrel** [comment]
@alanisaac Could also prolly use `StrEnum` directly. See [here](https://docs.python.org/3.11/library/enum.html#enum.StrEnum).

**Comment by debajyotid2** [comment]
@alanisaac We could probably use `StrEnum` directly - see [here](https://docs.python.org/3.11/library/enum.html#enum.StrEnum).

**Comment by alanisaac** [comment]
> @alanisaac We could probably use `StrEnum` directly - see [here](https://docs.python.org/3.11/library/enum.html#enum.StrEnum).

Oh neat, that's new(er).  I'm still used to writing in older versions.  Will update

**Comment by debajyotid2** [comment]
LGTM

**Pull request merged**
