### PR TITLE
Make a `vitest` unit test for the Rules Engine Python `whl`

### PR DESCRIPTION
**Pull request by thadk**
From the `heat-stack` folder, run `npm test app/utils/pyodide.test.ts` or see the new `whole heat-stack` Checks below. 

- [x] `npm run test` should pre-run the necessary python build commands, not too sure about dependencies ([see `package.json`](https://github.com/codeforboston/home-energy-analysis-tool/pull/109/files#diff-f6c1fe93fa912a1aa0226a19ccee962bd6b9b8077734e8877b3ec6a27b5bf4c8R23))
- [x] created vitest unit test of pyodide module based on Epic Stack [pro workshop testing solution](https://www.epicweb.dev/workshops/web-application-testing) in [misc.error-message.test.ts](https://github.com/epicweb-dev/full-stack-testing/blob/main/exercises/04.unit-test/02.solution.spies/app/utils/misc.error-message.test.ts)
- [x] tweaked path of pyodide-env in test 
     - from `/pyodide-env` for browser 
     - to `public/pyodide-env` for `vitest` environment
- [x] used `engine.hdd(57, 60)` but we may ultimately want to use an alternative version of the [test_rules_engine/*.py](https://github.com/codeforboston/home-energy-analysis-tool/tree/main/rules-engine/tests/test_rules_engine) files
- [x] bumped minor pyodide version
- [x] fixed up linter to avoid errors, including `.eslintignore`
- [x] create the Github Action automation
- [x] disabled Epic Stack's `deploy` and `playwright` GitHub actions: 
     - Deploy not needed yet 
     - and Playwright is underutilized yet, slow, and jank-failed 1 out of 20 runs.
- [x] modify python Github Action to target v3.11.3 (matches Pyodide 0.24.1).
- [x] rebased to latest `main` and added new type definition requirements.txt to test and `public/pyodide-env` folder to make pass again.

Full output:
<details>

```

➜ npm test app/utils/pyodide.test.ts
zsh: correct 'test' to 'tests' [nyae]? n

> test
> pushd ../rules-engine && python3 -m venv venv && source venv/bin/activate && pip install -q build && python3 -m build && popd && vitest app/utils/pyodide.test.ts

~/gitrepos/home-energy-analysis-tool/rules-engine ~/gitrepos/home-energy-analysis-tool/heat-stack

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools)
* Getting build dependencies for sdist...
running egg_info
writing src/rules_engine.egg-info/PKG-INFO
writing dependency_links to src/rules_engine.egg-info/dependency_links.txt
writing requirements to src/rules_engine.egg-info/requires.txt
writing top-level names to src/rules_engine.egg-info/top_level.txt
reading manifest file 'src/rules_engine.egg-info/SOURCES.txt'
writing manifest file 'src/rules_engine.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing src/rules_engine.egg-info/PKG-INFO
writing dependency_links to src/rules_engine.egg-info/dependency_links.txt
writing requirements to src/rules_engine.egg-info/requires.txt
writing top-level names to src/rules_engine.egg-info/top_level.txt
reading manifest file 'src/rules_engine.egg-info/SOURCES.txt'
writing manifest file 'src/rules_engine.egg-info/SOURCES.txt'
running check
creating rules-engine-0.0.1
creating rules-engine-0.0.1/src
creating rules-engine-0.0.1/src/rules_engine
creating rules-engine-0.0.1/src/rules_engine.egg-info
copying files to rules-engine-0.0.1...
copying README.md -> rules-engine-0.0.1
copying pyproject.toml -> rules-engine-0.0.1
copying src/rules_engine/__init__.py -> rules-engine-0.0.1/src/rules_engine
copying src/rules_engine/engine.py -> rules-engine-0.0.1/src/rules_engine
copying src/rules_engine.egg-info/PKG-INFO -> rules-engine-0.0.1/src/rules_engine.egg-info
copying src/rules_engine.egg-info/SOURCES.txt -> rules-engine-0.0.1/src/rules_engine.egg-info
copying src/rules_engine.egg-info/dependency_links.txt -> rules-engine-0.0.1/src/rules_engine.egg-info
copying src/rules_engine.egg-info/requires.txt -> rules-engine-0.0.1/src/rules_engine.egg-info
copying src/rules_engine.egg-info/top_level.txt -> rules-engine-0.0.1/src/rules_engine.egg-info
copying src/rules_engine.egg-info/SOURCES.txt -> rules-engine-0.0.1/src/rules_engine.egg-info
Writing rules-engine-0.0.1/setup.cfg
Creating tar archive
removing 'rules-engine-0.0.1' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools)
* Getting build dependencies for wheel...
running egg_info
writing src/rules_engine.egg-info/PKG-INFO
writing dependency_links to src/rules_engine.egg-info/dependency_links.txt
writing requirements to src/rules_engine.egg-info/requires.txt
writing top-level names to src/rules_engine.egg-info/top_level.txt
reading manifest file 'src/rules_engine.egg-info/SOURCES.txt'
writing manifest file 'src/rules_engine.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/rules_engine
copying src/rules_engine/__init__.py -> build/lib/rules_engine
copying src/rules_engine/engine.py -> build/lib/rules_engine
running egg_info
writing src/rules_engine.egg-info/PKG-INFO
writing dependency_links to src/rules_engine.egg-info/dependency_links.txt
writing requirements to src/rules_engine.egg-info/requires.txt
writing top-level names to src/rules_engine.egg-info/top_level.txt
reading manifest file 'src/rules_engine.egg-info/SOURCES.txt'
writing manifest file 'src/rules_engine.egg-info/SOURCES.txt'
installing to build/bdist.macosx-13-arm64/wheel
running install
running install_lib
creating build/bdist.macosx-13-arm64
creating build/bdist.macosx-13-arm64/wheel
creating build/bdist.macosx-13-arm64/wheel/rules_engine
copying build/lib/rules_engine/__init__.py -> build/bdist.macosx-13-arm64/wheel/rules_engine
copying build/lib/rules_engine/engine.py -> build/bdist.macosx-13-arm64/wheel/rules_engine
running install_egg_info
Copying src/rules_engine.egg-info to build/bdist.macosx-13-arm64/wheel/rules_engine-0.0.1-py3.11.egg-info
running install_scripts
creating build/bdist.macosx-13-arm64/wheel/rules_engine-0.0.1.dist-info/WHEEL
creating '/Users/thadk/gitrepos/home-energy-analysis-tool/rules-engine/dist/.tmp-k18bytp9/rules_engine-0.0.1-py3-none-any.whl' and adding 'build/bdist.macosx-13-arm64/wheel' to it
adding 'rules_engine/__init__.py'
adding 'rules_engine/engine.py'
adding 'rules_engine-0.0.1.dist-info/METADATA'
adding 'rules_engine-0.0.1.dist-info/WHEEL'
adding 'rules_engine-0.0.1.dist-info/top_level.txt'
adding 'rules_engine-0.0.1.dist-info/RECORD'
removing build/bdist.macosx-13-arm64/wheel
Successfully built rules-engine-0.0.1.tar.gz and rules_engine-0.0.1-py3-none-any.whl
~/gitrepos/home-energy-analysis-tool/heat-stack

 DEV  v0.34.4 /Users/thadk/gitrepos/home-energy-analysis-tool/heat-stack

stdout | app/utils/pyodide.test.ts > pyodide loads
Loading numpy

stdout | app/utils/pyodide.test.ts > pyodide loads
Loaded numpy
Loading rules_engine

stdout | app/utils/pyodide.test.ts > pyodide loads
Loaded rules_engine

 ✓ app/utils/pyodide.test.ts (1) 1667ms
   ✓ pyodide loads 1665ms

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  01:59:23
   Duration  2.21s (transform 70ms, setup 387ms, collect 4ms, tests 1.67s, environment 0ms, prepare 41ms)
```

</details>

Test output:

### Intentional fail:
image

### Pass:
image

### CODE REVIEW

**Comment by thadk** [comment]
Making this a draft PR: Oops, I made the branch off an outdated branch so the readme would be altered. I'll recreate this PR branch correctly tomorrow.

**Comment by thadk** [comment]
@alanisaac Welcome to review. I also changed the Github Action python target version to 3.11.3 which is the current [pyodide release's version](https://pyodide.org/en/stable/project/changelog.html) .

**Review by alanisaac — COMMENTED** [review]
I notice in `public/pyodide-env` that it looks like there's a binary related to the Python dependencies used (like `numpy`).  Are those meant to be committed to source control?

**Comment by thadk** [comment]
@alanisaac Yep, that folder re-hosts locally:
-  the python environment binary WebAssembly files, copied from the Pyodide `node_modules` library folder
- and `whl` files (like for numpy library) which I manually extracted from the Pyodide 0.24.1 [~212mb release ](https://github.com/pyodide/pyodide/releases) `pyodide-0.24.1.tar.bz2`. 
    - This is mostly for running offline. If it can't find any library you try to access, pyodide will also try to download them from the default content delivery network (cdn).

Both of these binaries have to be fetched at Javascript run-time and aren't bundleable along with the Pyodide Javascript library itself.

**Comment by thadk** [comment]
I tried to run pytest and the [test_engine.py](https://github.com/codeforboston/home-energy-analysis-tool/blob/main/rules-engine/tests/test_rules_engine/test_engine.py) from within the Pyodide environment but running `pytest.main()` within Pyodide after loading that file contents crashes everything. 

If we want an internal Pyodide test like that, we might need to wrap those assertions with some other library than `pytest`. On ChatGPT or on StackOverflow, I saw  [`unittest`](https://docs.python.org/3/library/unittest.html) suggested but I'm not sure.

**Review by alanisaac — APPROVED** [review]

**Comment by jkoren** [comment]
Thad will:
- revert root.tsx to remove changes made by linter (removed ; and changed ' to ")
- Modify linter to give warnings but not make changes

**Comment by plocket** [comment]
Also, just to be sure, close the block comment at https://github.com/codeforboston/home-energy-analysis-tool/pull/109/files#diff-ae03e02fefef517ad9aa21f08290622cf90b06ccfb95f94362b273a43a70aa9eR16

**Pull request merged**
